from collections import namedtuple

Number = namedtuple("Number", "value")
Id = namedtuple("Id", "name")
Not = namedtuple("Not", "term")
Equal = namedtuple("Equal", "left right")
NotEqual = namedtuple("NotEqual", "left right")
Add = namedtuple("Add", "left right")
Substract = namedtuple("Substract", "left right")
Multiply = namedtuple("Multiply", "left right")
Divide = namedtuple("Divide", "left right")
Call = namedtuple("Call", "calle args")
Return = namedtuple("Return", "term")
Block = namedtuple("Block", "statements")
If = namedtuple("If", "conditional consequence alternative")
Function = namedtuple("Function", "name parameters body")
Var = namedtuple("Var", "name value")
Assign = namedtuple("Assign", "name value")
While = namedtuple("While", "conditional body")
